function prob = gaussPDF(Data, Mu, Sigma)

% Likelihood of datapoint(s) to be generated by a Gaussian parameterized by center and covariance.

[nbVar,nbData] = size(Data);
Data = Data' - repmat(Mu',nbData,1);
prob = sum((Data/Sigma).*Data, 2);
prob = exp(-0.5*prob) / sqrt((2*pi)^nbVar * abs(det(Sigma)) + realmin);

end
